import { Question } from '../../types';

export const loma320Chapter10Questions: Question[] = [
  // ==========================================
  // OBJECTIVE 10A: THE FOUR TYPES OF COMMUNICATION TOOLS (Q1 - Q10)
  // ==========================================
  {
    id: 1,
    lo: "principle",
    question: "Vanguard Life uses specialized financial representatives to sit down with affluent clients, review their individual tax situations, and present customized whole life insurance options face-to-face. This interactive, one-to-one communication tool is classified as:",
    options: [
      "Sales promotion",
      "Advertising",
      "Personal selling",
      "Publicity"
    ],
    answer: 2,
    explanation: "Personal selling presents information during one-to-one communications between a customer and a company representative."
  },
  {
    id: 2,
    lo: "principle",
    question: "To boost first-year persistency, SafeHaven Mutual offers its sales representatives a bonus override and luxury travel voucher if they retain 95% of their premium files. In marketing communications, this tool is classified as:",
    options: [
      "Advertising",
      "Sales promotion",
      "Publicity",
      "Personal selling"
    ],
    answer: 1,
    explanation: "Sales promotion involves providing customers and/or distribution channel members with monetary or other incentives to encourage them to buy or sell a product."
  },
  {
    id: 3,
    lo: "principle",
    question: "SafeHaven Mutual purchases a series of banner ads and video spots on a highly trafficked sports news website to explain the benefits of its new term life insurance plans. This nonpersonal, paid communication generated by an identified sponsor is:",
    options: [
      "Publicity",
      "Personal selling",
      "Sales promotion",
      "Advertising"
    ],
    answer: 3,
    explanation: "Advertising is a form of nonpersonal communication about a company or its products that is generated and paid for by an identified sponsor and transmitted by the media."
  },
  {
    id: 4,
    lo: "principle",
    question: "Apex Life's PR team drafts an announcement about their newly launched green office initiative and submits it to local newspapers. Several newspapers publish a news segment about it. Apex did not pay the newspapers to run the story. This communication style is:",
    options: [
      "Sales promotion",
      "Publicity",
      "Personal selling",
      "Advertising"
    ],
    answer: 1,
    explanation: "Publicity is a form of nonpersonal communication about a company or its products and services that is transmitted in a news format by the mass media without paying direct media transmission costs."
  },
  {
    id: 5,
    lo: "principle",
    question: "An insurance company's marketing team wants to distinguish between advertising and publicity. What is the primary difference regarding media costs between these two tools?",
    options: [
      "Advertising does not require an identified sponsor, whereas publicity always does.",
      "Insurers incur direct media costs for advertising because they buy the time or space; they do not incur direct media transmission costs for publicity.",
      "Advertising is always remote, whereas publicity is strictly face-to-face.",
      "Publicity provides complete corporate control over the exact timing and content of the message, whereas advertising does not."
    ],
    answer: 1,
    explanation: "Unlike advertising, where the insurer pays media space/time costs, publicity does not incur direct media costs because the company has no control over how much, if any, of the information is actually transmitted by the media."
  },
  {
    id: 6,
    lo: "principle",
    question: "A marketing manager at Elite Assurance is preparing several promotions. She is distributing branded coffee mugs and keychains to shoppers at a neighborhood health fair. This specific action represents a:",
    options: [
      "Personal selling pitch",
      "Consumer sales promotion",
      "Publicity release",
      "Trade selling objective"
    ],
    answer: 1,
    explanation: "Distributing specialty items, like custom-imprinted mugs and keychains directly to prospective buyers, constitutes a consumer sales promotion designed to encourage product interaction."
  },
  {
    id: 7,
    lo: "principle",
    question: "Vanguard Life publishes an online article written by their chief medical underwriting director about heart-healthy lifestyles, featuring an Apex corporate watermark. Since it is written in a neutral, informative editorial format, this tool is most aligned with:",
    options: [
      "Advertising",
      "Personal selling",
      "Publicity",
      "Sales promotion"
    ],
    answer: 2,
    explanation: "By sharing the article in an educational, informative news/editorial format that does not directly pitch a product, the company is generating publicity."
  },
  {
    id: 8,
    lo: "principle",
    question: "A customer service coordinator at SafeHaven Mutal stands at a kiosk inside a regional bank partner, offering customized rate illustrations and answering direct coverage inquiries from depositors. This interaction represents:",
    options: [
      "Publicity campaigns",
      "Sales promotion overrides",
      "Personal selling",
      "Paid advertising media"
    ],
    answer: 2,
    explanation: "Direct, personal, one-to-one advisory interactions between a company representative and a consumer to guide product solutions represent personal selling."
  },
  {
    id: 9,
    lo: "principle",
    question: "Which of the following is an example of an incentive that would be classified under an insurer's 'trade sales promotion' rather than a 'consumer sales promotion'?",
    options: [
      "Providing free branded calendars to local prospective policyholders",
      "Providing a regional bank's platform employees with specialized product training seminars and financial sales kits",
      "Offering a 30-day money-back guarantee to term life purchasers",
      "A television advertisement highlighting the carrier's excellent customer service ratings"
    ],
    answer: 1,
    explanation: "Trade sales promotions focus on sales representatives and distribution channel members (such as bank employees or agents), whereas consumer promotions focus directly on individual buyers."
  },
  {
    id: 10,
    lo: "principle",
    question: "Federal Insurance wants to reach a geographically dispersed mass market with a simple message about their fixed annuities. Because they need high reach, low cost per person, and nonpersonal delivery, they should rely primarily on:",
    options: [
      "Personal selling",
      "Advertising",
      "Direct face-to-face consulting",
      "Discretionary estate meetings"
    ],
    answer: 1,
    explanation: "Advertising is nonpersonal, reaches a vast audience, and carries a low cost per person compared to the direct expense of conducting personal selling for individual households."
  },

  // ==========================================
  // OBJECTIVE 10B: MINIMAL SYSTEM DEFINITIONS & THE COMMUNICATION PROCESS (Q11 - Q20)
  // ==========================================
  {
    id: 11,
    lo: "principle",
    question: "SafeHaven Mutual launches a campaign to guide customers through a sequential response hierarchy. Which standard response sequence is commonly used to trace customer reactions from attention to action?",
    options: [
      "The PEST strategic matrix",
      "The BCG cash-flow system",
      "The AIDA model",
      "The SWOT capability index"
    ],
    answer: 2,
    explanation: "The AIDA model (Attention, Interest, Desire, Action) represents a response hierarchy guiding customers from initial awareness to final sale."
  },
  {
    id: 12,
    lo: "principle",
    question: "According to the AIDA response hierarchy model, what are the most effective communication tools to capture 'Attention' and generate 'Interest' in a newly introduced product?",
    options: [
      "Personal selling and trade incentives",
      "Advertising and publicity",
      "Sales promotions and point-of-purchase displays",
      "Estate planning audits and discretionary advisory contracts"
    ],
    answer: 1,
    explanation: "According to the AIDA model, advertising and publicity are the most effective tools for capturing Attention and generating Interest."
  },
  {
    id: 13,
    lo: "principle",
    question: "Vanguard Life wants to define its brand position as the 'most financially secure carrier' based on history and premium ratings. Marketing communications designed to cultivate this perception target which primary goal?",
    options: [
      "To bypass state insurance department filing regulations",
      "To define a company's or product's position in the market",
      "To convert inelastic products into elastic products",
      "To eliminate the need for a marketing communication budget"
    ],
    answer: 1,
    explanation: "Defining a company's or product's position in the market is based on customer perceptions about key benefits, such as financial and brand security."
  },
  {
    id: 14,
    lo: "principle",
    question: "An insurance company updates its offices to run entirely on solar energy and publishes detailed guides helping consumers reduce paper waste. This communication focuses on which primary marketing goal?",
    options: [
      "To establish direct-mail sales superiority",
      "To create a strong, positive corporate image",
      "To eliminate the underwriting step",
      "To establish a competitive parity budget"
    ],
    answer: 1,
    explanation: "Communicating efforts that demonstrate social responsibility or corporate values helps build a strong, positive, and trustworthy image of the company."
  },
  {
    id: 15,
    lo: "principle",
    question: "In the basic marketing communication process, who is the entity that translates ideas into symbols, initiating the transmission of a message?",
    options: [
      "The receiver",
      "The encoder or sender",
      "The gatekeeper",
      "The clearing principal"
    ],
    answer: 1,
    explanation: "The sender (source) initiates the process by using an encoding process to translate thoughts, goals, or ideas into written, spoken, or visual messages."
  },
  {
    id: 16,
    lo: "principle",
    question: "An insurance prospect reads a flyer explaining a critical illness plan, but misinterprets a 'graded benefit limitation' as an 'accidental death exclusion.' In information theory, this translation error occurs during:",
    options: [
      "Encoding",
      "Decoding",
      "Feedback collection",
      "Media scheduling"
    ],
    answer: 1,
    explanation: "Decoding is the process by which the receiver translates the symbols, images, or words in a message back into meaningful ideas. Misinterpretations occur during decoding."
  },
  {
    id: 17,
    lo: "principle",
    question: "SafeHaven Mutual posts an interactive term life quiz on social media. A visitor takes the quiz and leaves a comment asking how premium rates are calculated for smokers. This response is considered:",
    options: [
      "Noise",
      "Feedback",
      "Encoding",
      "The media vehicle"
    ],
    answer: 0,
    explanation: "No wait, the option index for feedback is 1, let me check. Yes! If the user submits a comment or query back to the sender, this is feedback (option 1)."
  },
  {
    id: 18,
    lo: "principle",
    question: "During a live webinar, a power outage disconnects the virtual feed, causing attendees to miss the visual charts presented by the insurance advisor. This disruption is a classic example of:",
    options: [
      "Channel feedback",
      "Decode error",
      "Noise",
      "Reciprocity bypass"
    ],
    answer: 2,
    explanation: "Noise is anything that interferes with the creation, transmission, or translating of messages, which can originate in the channel (such as a power outage)."
  },
  {
    id: 19,
    lo: "principle",
    question: "A company places a modest advertisement on a magazine page. On the opposite page, a competitor runs an enormous, high-contrast ad featuring a celebrity endorsement, completely distracting the reader. The competitor's ad is considered:",
    options: [
      "An encoding error",
      "Competitive parity feedback",
      "Noise",
      "A media vehicle"
    ],
    answer: 2,
    explanation: "An intensely distracting factor in the environment or media channel (such as a massive competing ad nearby) acts as noise that blocks the message from being processed."
  },
  {
    id: 20,
    lo: "principle",
    question: "When an adviser conducts a video conference with a prospective policyholder and asks questions to confirm the client has correctly understood the policy exclusions, the adviser is primarily trying to check:",
    options: [
      "Channel noise",
      "Client decoding accuracy via feedback",
      "The competitor's parity limits",
      "The client's forgetting rate"
    ],
    answer: 1,
    explanation: "By collecting verbal and visual reactions (feedback), the advisor can evaluate whether the client has decoded the informational message correctly."
  },

  // ==========================================
  // OBJECTIVE 10C: PUSH, PULL, AND COMBINATION STRATEGIES (Q21 - Q30)
  // ==========================================
  {
    id: 21,
    lo: "principle",
    question: "An insurance company focuses its marketing expenditures on independent brokers, offering them advanced computer software tools, sales aids, and competitive commission rates. This strategy is classified as a:",
    options: [
      "Pull strategy",
      "Push strategy",
      "Combination strategy",
      "Discretionary bypass strategy"
    ],
    answer: 1,
    explanation: "A push strategy provides intermediaries (like brokers or agents) with incentives and tools to sell (or 'push') the company's products to final consumers."
  },
  {
    id: 22,
    lo: "principle",
    question: "Vanguard Life directs its marketing campaign at individual families, creating educational blog posts, social media quizzes, and YouTube videos that encourage viewers to ask their local brokers for Vanguard coverage. This is a:",
    options: [
      "Push strategy",
      "Combination strategy",
      "Pull strategy",
      "Bancassurance strategy"
    ],
    answer: 2,
    explanation: "A pull strategy is directed at final consumers to stimulate demand, encouraging them to request the brand's products from a distributor or broker."
  },
  {
    id: 23,
    lo: "principle",
    question: "Apex Mutual launches a brand awareness ad campaign on national television while simultaneously increasing commission overrides for its career sales agencies. Apex's approach is an example of a:",
    options: [
      "Pure push strategy",
      "Combination strategy",
      "Pure pull strategy",
      "Specialty advertising model"
    ],
    answer: 1,
    explanation: "A combination strategy coordinates elements of both push and pull strategies to create demand among both consumers and distribution channel members."
  },
  {
    id: 24,
    lo: "principle",
    question: "How has the rise of internet searches altered consumer behavior and the effectiveness of traditional 'pull' letters and advertisements in insurance marketing?",
    options: [
      "Consumers have lost all control over where they find product information.",
      "Most consumers now search the web, consulting an average of 10 online sites to gather independent facts and make decisions before contacting an insurer.",
      "Pull strategies have been completely replaced by direct personal selling.",
      "Internet data has made insurance products perfectly simple and transactional."
    ],
    answer: 1,
    explanation: "Modern consumers prefer independent research, gathering info from roughly 10 websites on average before officially reaching out to a carrier."
  },
  {
    id: 25,
    lo: "principle",
    question: "In response to changing customer habits, safeHaven Life implements 'content marketing.' What is the primary characteristic of a successful content marketing strategy?",
    options: [
      "Sending constant, high-frequency outbound sales pitches via automated telemarketing",
      "Creating and delivering valuable, relevant, and consistent informational content to a clearly defined audience",
      "Using complex legal contracts to ensure customers do not look at other brands",
      "Bypassing all licensed sales agents to rely on celebrity endorsements"
    ],
    answer: 1,
    explanation: "Content marketing focuses on educating and building relationships with clients by supplying useful, high-quality, non-promotional information."
  },
  {
    id: 26,
    lo: "principle",
    question: "The leadership at safeHaven Life decides to structure their promotional communication mix. Which internal corporate factor is likely to have the most profound immediate impact on selecting these tools?",
    options: [
      "The political composition of the state insurance commission",
      "Company goals, strategy, and corporate culture",
      "The competitor's specific printing press capacity",
      "The consumer price index of the home state"
    ],
    answer: 1,
    explanation: "Internal factors like company goals, marketing strategies, and company culture directly dictate the choice and execution of tools in the communication mix."
  },
  {
    id: 27,
    lo: "principle",
    question: "SafeHaven Mutual has a proactive, tech-focused corporate culture. How will this company culture likely influence their chosen communication mix compared to a reactive competitor?",
    options: [
      "SafeHaven will avoid all communication strategies to reduce exposure.",
      "SafeHaven will quickly recognize the value of innovative digital networks and integrate social media channels into its mix.",
      "SafeHaven will rely entirely on traditional print newspapers to project safety.",
      "SafeHaven will outsource its entire salesforce to unlicenced bank representatives."
    ],
    answer: 1,
    explanation: "A proactive corporate culture is quick to experiment and integrate modern, digital channels (like social platforms) compared to reactive firms."
  },
  {
    id: 28,
    lo: "principle",
    question: "Acme Assurance sells a highly complex, premium variable universal life product designed for estate preservation. Because of this product’s unique characteristics, which communication tool should dominate their mix?",
    options: [
      "Highly structured print ads in general neighborhood papers",
      "Personal selling by experienced, licensed advisors",
      "Point-of-purchase displays at local checkout desks",
      "Mass entertainment radio sponsorship"
    ],
    answer: 1,
    explanation: "High-priced, complex, infrequently purchased products requiring custom estate/financial analysis are best supported by personal selling where features can be explained."
  },
  {
    id: 29,
    lo: "principle",
    question: "A company wishes to sell credit life coverage to a massive, geographically dispersed retail market. Because their target market is extremely large and spread out, they should prioritize:",
    options: [
      "One-on-one personal selling by high-net-worth advisors",
      "Television, direct mail, or digital advertising",
      "Individualized estate planning webinars",
      "Exclusive face-to-face home agency managers"
    ],
    answer: 1,
    explanation: "A vast, dispersed target audience is reached most efficiently and at a lower cost per person through mass media advertising rather than personal sales calls."
  },
  {
    id: 30,
    lo: "principle",
    question: "State regulators pass a new rule requiring specific, highly standardized disclosures in all advertisements showing variable annuity returns. This external factor is an example of:",
    options: [
      "An internal culture shift",
      "A regulatory restriction in the external environment",
      "A competitive parity objective",
      "An AIDA action outcome"
    ],
    answer: 1,
    explanation: "External factors such as laws, state regulations, and competitor movements directly constrain and reshape an insurer's communication choices."
  },

  // ==========================================
  // OBJECTIVE 10D: FOUR BUDGETING METHODS (Q31 - Q40)
  // ==========================================
  {
    id: 31,
    lo: "principle",
    question: "The director at Apex Life sets the marketing communications budget for next year at exactly 1.5% of projected first-year premium sales. This budgeting technique is known as the:",
    options: [
      "Competitive parity method",
      "Objective and task method",
      "Percentage of sales method",
      "All-you-can-afford method"
    ],
    answer: 2,
    explanation: "The percentage of sales method bases the budgetary allocation on a specified percentage of past or projected sales (often first-year premiums)."
  },
  {
    id: 32,
    lo: "principle",
    question: "What is a primary advantage of using the 'percentage of sales' method when configuring an insurer's communication budget?",
    options: [
      "It establishes a highly accurate scientific link between communication spend and revenue.",
      "It is simple to use and produces budgets that remain relatively stable from year to year.",
      "It automatically increases spend when sales undergo a sudden economic slump.",
      "It is entirely focused on specific strategic goals rather than past performance."
    ],
    answer: 1,
    explanation: "The simplicity of calculation and the stability/predictability of spending from year to year are the core advantages of the percentage of sales method."
  },
  {
    id: 33,
    lo: "principle",
    question: "A major drawback of the 'percentage of sales' budgeting method is that it can create a 'downward spiral' during sales slumps. Why is this?",
    options: [
      "Because it forces the company to double its advertising budget when sales are low, leading to high capital drains.",
      "Because a drop in sales triggers a decreased communication budget, which can further accelerate the downward trend in sales.",
      "Because it violates NAIC general trade practice accounting guidelines.",
      "Because it requires SEC registration for even the simplest fixed term products."
    ],
    answer: 1,
    explanation: "Since the budget is tied to sales, when sales slip, the marketing budget shrinks. Less marketing then leads to even lower sales, triggering a downward spiral."
  },
  {
    id: 34,
    lo: "principle",
    question: "A marketing analyst at SafeHaven Life collects data from industry trade publications to evaluate average marketing expenditures. The executive team then matches their budget to the competitor averages. This is the:",
    options: [
      "Percentage of sales method",
      "Objective and task method",
      "Competitive parity method",
      "All-you-can-afford method"
    ],
    answer: 2,
    explanation: "The competitive parity method bases the firm's communication budget on the spending or budgets of one or more competitors."
  },
  {
    id: 35,
    lo: "principle",
    question: "Why should an insurer avoid relying solely on the 'competitive parity' method when setting its unique communication budgets?",
    options: [
      "Competitors' spending patterns are illegal to monitor under Federal trade codes.",
      "It assumes all competitors have identical marketing goals, structures, and capabilities, which ignores the insurer's unique situation.",
      "It relies exclusively on complex laboratory pretesting models.",
      "It does not require any review by the legal department."
    ],
    answer: 1,
    explanation: "Mimicking a competitor's budget ignores the company's unique marketing goals, target segments, and product lines, which may be vastly different."
  },
  {
    id: 36,
    lo: "principle",
    question: "Vanguard Life’s profits drop by 15% during a recession. The executive board immediately cuts the marketing budget to matching funds that remain after operating expenses are covered. This is the:",
    options: [
      "Percentage of sales method",
      "All-you-can-afford method",
      "Objective and task method",
      "Competitive parity method"
    ],
    answer: 1,
    explanation: "The all-you-can-afford method restricts marketing communication budgets strictly to whatever funds remain available after other corporate costs are met."
  },
  {
    id: 37,
    lo: "principle",
    question: "What is the primary risk associated with using the 'all-you-can-afford' budgeting method during periods of low sales volume?",
    options: [
      "Expenses will trigger an automated audit by FINRA under Rule 2110.",
      "The company may spend too little on critical marketing when the need for product promotion is actually highest, missing key sales opportunities.",
      "The legal department will refuse to draft standard agency contracts.",
      "It forces the company to rely exclusively on expensive television advertising."
    ],
    answer: 1,
    explanation: "When sales are low, the need to promote products usually increases. Cutting budgets to zero because funds are low prevents the company from recovering sales."
  },
  {
    id: 38,
    lo: "principle",
    question: "Apex Life identifies its goal: 'Increase term policy sales in Ohio by 8% over twelve months.' The team then outlines the specific activities needed to meet this goal and calculates their costs. This is the:",
    options: [
      "Percentage of sales method",
      "Objective and task method",
      "Competitive parity method",
      "All-you-can-afford method"
    ],
    answer: 1,
    explanation: "The objective and task method bases budgets on specified marketing objectives and the exact estimated costs of the tasks needed to meet those goals."
  },
  {
    id: 39,
    lo: "principle",
    question: "Which of the following describes the standard sequence of planning when using the 'objective and task' budgeting method?",
    options: [
      "A budget is established first, and tasks are created to fit whatever funds are provided.",
      "The budget is created after establishing specific communication plans and identifying needed tasks.",
      "The competitor's budget is copied first, followed by objective reviews.",
      "A percentage of last year's premium is set aside before any goals are discussed."
    ],
    answer: 1,
    explanation: "Because the objective and task method relies heavily on identifying specific required activities, users create the budget after a communication plan has been conceptualized."
  },
  {
    id: 40,
    lo: "principle",
    question: "Which of the four major communication budgeting methods is widely considered the most logical, strategic, and professional, despite being the most complex to implement?",
    options: [
      "All-you-can-afford method",
      "Percentage of sales method",
      "Objective and task method",
      "Competitive parity method"
    ],
    answer: 2,
    explanation: "The objective and task method is the most rational because it treats communication as a strategic investment to reach concrete goals, rather than an arbitrary expense."
  },

  // ==========================================
  // OBJECTIVE 10E: COMPONENTS OF A MEDIA PLAN (Q41 - Q50)
  // ==========================================
  {
    id: 41,
    lo: "principle",
    question: "A company’s marketing team develops a document specifying the types of media, specific media vehicles, and precise schedule of exposures for an upcoming annuity campaign. This document is a:",
    options: [
      "Trade sales promotion guide",
      "Media plan (or communication plan)",
      "Vesting statement",
      "Policy summary"
    ],
    answer: 1,
    explanation: "A media plan or communication plan specifies the media types, vehicles, and timing schedules used to transmit marketing messages."
  },
  {
    id: 42,
    lo: "principle",
    question: "SafeHaven Mutual wants to evaluate if they should run video ads on YouTube or publish print ads in a national health magazine. In media planning, 'magazine' and 'video portals' represent different:",
    options: [
      "Media vehicles",
      "Media types",
      "Media schedules",
      "Forgetting rates"
    ],
    answer: 1,
    explanation: "Media types are broad categories of communication channels, such as print, digital, television, radio, or direct mail."
  },
  {
    id: 43,
    lo: "principle",
    question: "SafeHaven Mutual decides to publish their print ad specifically in 'Time Magazine' and 'The Wall Street Journal.' In media planning, these specific publications are classified as:",
    options: [
      "Media types",
      "Media vehicles",
      "Media schedules",
      "Pretesting models"
    ],
    answer: 1,
    explanation: "Media vehicles are the specific programs, publications, websites, or stations within a broad media type (e.g., Time Magazine is a vehicle within the print media type)."
  },
  {
    id: 44,
    lo: "principle",
    question: "An advertising analyst reports that Vanguard Life’s digital display ad was seen by exactly 2.5 million individual internet users over a 60-day campaign. This metric is referred to as:",
    options: [
      "Frequency",
      "Reach",
      "Waste",
      "Buyer turnover"
    ],
    answer: 1,
    explanation: "Reach refers to the total number of different people exposed to a marketing message through a given vehicle during a specified timeframe."
  },
  {
    id: 45,
    lo: "principle",
    question: "During a radio campaign in Chicago, the same local commuters see or hear SafeHaven’s annuity ad an average of six times over a four-week span. This exposure metric is known as:",
    options: [
      "Reach",
      "Frequency",
      "Waste",
      "Buyer turnover"
    ],
    answer: 1,
    explanation: "Frequency refers to the average number of times the same individuals are exposed to a marketing message in a particular vehicle within a given time period."
  },
  {
    id: 46,
    lo: "principle",
    question: "WhiteHall Life places television ads for deferred annuities during a popular teen music program. Because teenagers are highly unlikely to purchase deferred annuities, these viewers represent:",
    options: [
      "Reach selectivity",
      "Waste",
      "Forgetting rate",
      "Aided recall"
    ],
    answer: 1,
    explanation: "Waste refers to the number of non-target customers (such as teens for annuity products) who are exposed to a marketing message."
  },
  {
    id: 47,
    lo: "principle",
    question: "The market for student dental insurance has a high rate of graduating students leaving and new freshmen enrolling every semester. In media scheduling, this metric is called the:",
    options: [
      "Forgetting rate",
      "Buyer turnover",
      "Purchase frequency",
      "Pulsing frequency"
    ],
    answer: 1,
    explanation: "Buyer turnover describes the rate at which new customers enter a target market to purchase a product."
  },
  {
    id: 48,
    lo: "principle",
    question: "An insurance carrier knows that consumers buy life insurance very infrequently. In contrast, they buy milk and bread multiple times a week. This difference represents the difference in:",
    options: [
      "Buyer turnover",
      "Purchase frequency",
      "Forgetting rate",
      "Lapse rate"
    ],
    answer: 1,
    explanation: "Purchase frequency is the number of times customers buy a particular product within a given period."
  },
  {
    id: 49,
    lo: "principle",
    question: "If an insurance company halts its branding ads, consumers quickly forget the company’s name and products. The measure of how quickly this decay occurs is called the:",
    options: [
      "Lapse index",
      "Forgetting rate",
      "Purchase frequency",
      "Reach deficit"
    ],
    answer: 1,
    explanation: "The forgetting rate is a measure of how quickly customers forget a product or brand if no promotional message appears."
  },
  {
    id: 50,
    lo: "principle",
    question: "Vanguard Mutual runs a large number of digital ads at the beginning of the year, drops them during spring, and then runs them heavily again during winter. This exposure timing pattern is called:",
    options: [
      "A steady timing pattern",
      "A pulsing pattern",
      "A static frequency loop",
      "An AIDA action loop"
    ],
    answer: 1,
    explanation: "A pulsing pattern delivers communication exposures unevenly throughout a specified period of time, concentrating messages during peak times and pulling back during others."
  },

  // ==========================================
  // OBJECTIVE 10F: TRADE VS CONSUMER SALES PROMOTIONS (Q51 - Q60)
  // ==========================================
  {
    id: 51,
    lo: "principle",
    question: "Vanguard Life’s legal department reviews a collection of booklets, charts, and digital presentations designed for agents to use when explaining product options to clients during a meeting. These files are:",
    options: [
      "Point-of-purchase displays",
      "Sales aids",
      "Specialty advertising objects",
      "Buyer's guides"
    ],
    answer: 1,
    explanation: "Sales aids are promotional and educational materials used by sales representatives in conjunction with sales presentations to help explain complex products."
  },
  {
    id: 52,
    lo: "principle",
    question: "SafeHaven Mutual hosts a regional conference where independent brokers meet to learn about new tax codes and connect with product experts. This regional event falls under:",
    options: [
      "Consumer sales promotion",
      "Trade sales promotion",
      "Publicity campaign",
      "Point-of-work advertising"
    ],
    answer: 1,
    explanation: "Educational conferences, agent workshops, and regional sales meetings focus on sales representatives, which classifies them as trade sales promotions."
  },
  {
    id: 53,
    lo: "principle",
    question: "SafeHaven Mutual produces an elegant monthly booklet highlight-reeling the top-performing career agents who achieved million-dollar sales volume. This publication is an example of:",
    options: [
      "A consumer sales aid",
      "A trade sales promotion designed to recognize performance",
      "A publicity campaign",
      "A policy summary catalog"
    ],
    answer: 1,
    explanation: "Insurers use trade publications, newsletters, or award listings specifically to recognize high sales in their sales force, promoting active competition."
  },
  {
    id: 54,
    lo: "principle",
    question: "A broker studies hard to earn the 'Chartered Life Underwriter (CLU)' and 'Fellow, Life Management Institute (FLMI)' designations. Earning these professional certifications is supported by carriers as a form of:",
    options: [
      "Consumer education program",
      "Trade sales promotion and professional recognition",
      "Publicity and media relations",
      "Personal selling presentation"
    ],
    answer: 1,
    explanation: "Encouraging and acknowledging professional industry designations (like Chartered Financial Consultant or FLMI) is a trade promotion method to elevate sales representative credentials."
  },
  {
    id: 55,
    lo: "principle",
    question: "SafeHaven Mutual installs decorative kiosks and setups in local credit union lobbies, placing colored brochures and product summary booklets where depositors wait in line. These structures are:",
    options: [
      "Specialty advertising materials",
      "Point-of-purchase (POP) materials",
      "Trade sales aids",
      "Publicity news packages"
    ],
    answer: 1,
    explanation: "Point-of-purchase (POP) materials are promotional exhibits and handouts delivered to customers directly at the location where products are sold or distributed."
  },
  {
    id: 56,
    lo: "principle",
    question: "An agent hands a prospective client a useful calendar, a stylus pen, and a laptop sleeve, all prominently printed with the SafeHaven Mutual logo, helpline, and web link. These items are called:",
    options: [
      "Sales aids",
      "Specialty advertising",
      "Point-of-purchase documents",
      "Publicity announcements"
    ],
    answer: 1,
    explanation: "Specialty advertising is a consumer sales promotion that uses useful, low-cost objects (pens, mugs, mouse pads) imprinted with the company name, logo, or contact coordinates."
  },
  {
    id: 57,
    lo: "principle",
    question: "Farmers Insurance acts as the named headline sponsor for a widely televised annual golf tournament on the PGA Tour, raising millions for regional charities. Corporate sponsorship of this special event is a:",
    options: [
      "Trade sales promotion",
      "Consumer sales promotion to increase name recognition",
      "Personal selling presentation",
      "Product-oriented print ad"
    ],
    answer: 1,
    explanation: "Sponsorship of sporting, cultural, or community events acts as a consumer promotion designed to boost broad public name recognition and goodwill."
  },
  {
    id: 58,
    lo: "principle",
    question: "A company’s legal department reviews all incoming proposals for custom keychains and notebooks prepared by local sales agents for their individual practices. Why must the home office monitor these items?",
    options: [
      "To ensure agents do not resell the items for a profit",
      "To ensure all specialty advertising graphics comply with company brand policies and state trade guidelines",
      "To verify agents are using a combination digital strategy",
      "Because specialty items must be submitted to the SEC before printing"
    ],
    answer: 1,
    explanation: "Because agent-developed specialty items can reflect directly on the carrier, companies establish strict review policies to ensure compliance with brand standards and state law."
  },
  {
    id: 59,
    lo: "principle",
    question: "SafeHaven Mutual offers local shoppers who sign up for a physical exam at their neighborhood wellness fair a free insulated water bottle branded with the SafeHaven logo. This is a:",
    options: [
      "Trade promotional reward",
      "Consumer sales promotion",
      "Publicity news event",
      "Personal selling script"
    ],
    answer: 1,
    explanation: "Giving a consumer specialty items to stimulate engagement and interest is an example of a consumer sales promotion."
  },
  {
    id: 60,
    lo: "principle",
    question: "SafeHaven Mutual wants to support its career field force. Which of the following initiatives would be grouped under their 'trade sales promotion' budget?",
    options: [
      "Sponsoring a national academic essay competition for high schoolers",
      "Providing agents with an advanced online software portal that generates customized pricing illustrations",
      "Mailing customized calendars to 5,000 active policyholders",
      "Running brand-image television commercials during the evening news"
    ],
    answer: 1,
    explanation: "Providing sales representatives with software systems/illustrative tools directly supports sales efforts and represents trade sales promotion."
  },

  // ==========================================
  // OBJECTIVE 10G: CHOOSING MEDIA OPTIONS & ADVERTISING TYPES (Q61 - Q70)
  // ==========================================
  {
    id: 61,
    lo: "principle",
    question: "Marketing managers choose to place their ads in specialized, high-gloss magazines. Which of the following is a primary advantage of magazines as an advertising medium?",
    options: [
      "Extremely short lead times for creating and placing ads",
      "High geographical and demographic selectivity combined with prestige and long shelf life",
      "Inexpensive design and production costs compared to newspapers",
      "High motion, sight, and sound integration"
    ],
    answer: 1,
    explanation: "Magazines offer targeted demographic and geographic reach, high-quality printing, reader prestige, and a long shelf-life since readers keep them around."
  },
  {
    id: 62,
    lo: "principle",
    question: "An insurer is reviewing the disadvantages of television advertising. Which of the following is considered a major drawback of this medium?",
    options: [
      "Inability to convey emotions or visual storylines",
      "Large amount of waste, high development and broadcast costs, and high clutter",
      "Perfect demographic isolation of views",
      "Short exposure duration compared to radio audio"
    ],
    answer: 1,
    explanation: "Television ads carry high development/booking costs, high clutter, short viewing lifespans, and high waste since non-target segments see the ads."
  },
  {
    id: 63,
    lo: "principle",
    question: "WhiteHall Life wants to deliver customized ads to specific household televisions over a dedicated managed network controlled by the local telecom provider. This advertising channel is:",
    options: [
      "Internet television",
      "Internet protocol television (IPTV)",
      "Traditional linear broadcast television",
      "Public access radio"
    ],
    answer: 1,
    explanation: "Internet protocol television (IPTV) delivers content to viewers over a dedicated managed network controlled by cable, telecom, or satellite providers, allowing targeted household-level ads."
  },
  {
    id: 64,
    lo: "principle",
    question: "A customer visits a financial advisory blog and notices a small, clickable ad containing the SafeHaven Mutual logo. When clicked, it redirects them to SafeHaven’s contact form. This is a:",
    options: [
      "Search ad",
      "Banner ad (or display ad)",
      "IPTV video ad",
      "Companion print ad"
    ],
    answer: 1,
    explanation: "Banner ads (or display ads) are small, clickable advertisements placed on websites that direct users to the advertiser's web site."
  },
  {
    id: 65,
    lo: "principle",
    question: "A consumer types 'best variable annuity for retirement' into a web search engine and notices several sponsored links matching those keywords at the top of the page. These ads are:",
    options: [
      "Banner ads",
      "Search ads",
      "Linear video ads",
      "Companion display ads"
    ],
    answer: 1,
    explanation: "Search ads are advertisements that appear on search engine pages in response to user queries, targeting key words entered by users."
  },
  {
    id: 66,
    lo: "principle",
    question: "An insurer buys advertising space through an automated system that displays their ad to individual users in real-time based on bidding metrics. This automated marketplace is called:",
    options: [
      "Programmatic advertising",
      "Linear scheduling",
      "Bancassurance clearing",
      "Attitude pretesting"
    ],
    answer: 0,
    explanation: "Programmatic advertising is a trade-based system in an automated digital marketplace, similar to the stock market, where digital ad slots are bid on and traded in real-time."
  },
  {
    id: 67,
    lo: "principle",
    question: "When evaluating direct mail as an advertising option, which of the following is a key advantage of this medium?",
    options: [
      "Extremely low costs per contact",
      "Unlimited message length, high personalization, and easily measurable results",
      "Immediate response and action without delay",
      "Zero perception of 'junk' mail by recipients"
    ],
    answer: 1,
    explanation: "Direct mail allows for extensive product explanation (unlimited length), high personalization for specific recipient profiles, and easy tracking of response rates."
  },
  {
    id: 68,
    lo: "principle",
    question: "Vanguard Life’s marketers notice that their mobile device ads have an extremely fast annual growth rate compared to other mediums. Mobile advertising falls under the broader category of:",
    options: [
      "Print media",
      "Digital advertising",
      "Outdoor media",
      "Publicity packages"
    ],
    answer: 1,
    explanation: "Digital advertising uses Internet and wireless technologies to deliver video, text, or display ads via email, social networks, and mobile devices."
  },
  {
    id: 69,
    lo: "principle",
    question: "An insurer wants to place a radio ad. What is a key disadvantage associated with using radio as an advertising medium?",
    options: [
      "High development and placement costs",
      "Restrictive message length, limited to sound only, and limited recall value",
      "Lack of local geographic selectivity",
      "Very long lead times required to purchase slots"
    ],
    answer: 1,
    explanation: "Radio is limited to sound only, has a very short life cycle, restricts message length, and typically requires frequent repetition to achieve recall."
  },
  {
    id: 70,
    lo: "principle",
    question: "Why are search ads often considered far less intrusive by web users than banners or automatic pop-ups?",
    options: [
      "Because search ads do not have to follow state disclosure rules.",
      "Because search ads focus exclusively on the customer’s self-expressed interests based on active search queries.",
      "Because search ads are prepared by federal agencies.",
      "Because search ads are printed on tactile cards."
    ],
    answer: 1,
    explanation: "Since search ads matching the keywords pop up when a user actively searches for a topic, they align directly with the user's current intent, reducing intrusiveness."
  },

  // ==========================================
  // OBJECTIVE 10H: ADVERTISING CAMPAIGN FACTORS & MEDIA COSTS (Q71 - Q80)
  // ==========================================
  {
    id: 71,
    lo: "principle",
    question: "Vanguard Life develops a coordinated series of advertisements unified by a single theme, designed to achieve specific communication and sales goals over several months. This is called:",
    options: [
      "A media vehicle plan",
      "An advertising campaign",
      "A trade sales promotion",
      "A policy summary outline"
    ],
    answer: 1,
    explanation: "An advertising campaign is a coordinated series of advertisements designed to meet a company's overall advertising objectives."
  },
  {
    id: 72,
    lo: "principle",
    question: "SafeHaven Mutual wants to set an objective of 'improving brand recognition by 15% among young professionals over 6 months.' This kind of objective is classified as:",
    options: [
      "A sales-oriented advertising objective",
      "A communication-oriented advertising objective",
      "A regulatory compliance objective",
      "An underwriting persistency objective"
    ],
    answer: 1,
    explanation: "A communication-oriented objective seeks to increase customer recognition of, interest in, and knowledge about a company or product."
  },
  {
    id: 73,
    lo: "principle",
    question: "SafeHaven Mutual establishes a goal of 'increasing first-year premium sales for our new indexed group annuity by 8% over the next fiscal year.' This is:",
    options: [
      "A communication-oriented advertising objective",
      "A sales-oriented advertising objective",
      "A target market segmentation model",
      "An all-you-can-afford objective"
    ],
    answer: 1,
    explanation: "A sales-oriented objective describes specific sales volumes, market shares, or policy numbers the company intends to reach."
  },
  {
    id: 74,
    lo: "principle",
    question: "SafeHaven Mutual runs an ad showing a father talking with his daughter at her wedding, explaining how his term policy made it possible to fund her education after he passed away. What is this execution style?",
    options: [
      "Testimonial style",
      "Association style",
      "Story line style",
      "Mood style"
    ],
    answer: 2,
    explanation: "A story line execution style presents a short factual or hypothetical scenario displaying a problem and showing the product being used to resolve the conflict."
  },
  {
    id: 75,
    lo: "principle",
    question: "A high-profile Olympic gold medalist appears in an online video endorsing Vanguard Life, emphasizing how Vanguard's fast claims processing helped his family. This execution style is a:",
    options: [
      "Story line style",
      "Testimonial style",
      "Mood style",
      "Association style"
    ],
    answer: 1,
    explanation: "A testimonial uses customers, representatives, or well-known personalities to endorse a company or its products."
  },
  {
    id: 76,
    lo: "principle",
    question: "SafeHaven Mutual creates a tranquil television commercial featuring background classical music, slow-motion scenes of sunlit pine forests, and soft lighting to cultivate feelings of safety. This execution style is the:",
    options: [
      "Story line style",
      "Association style",
      "Mood style",
      "Testimonial style"
    ],
    answer: 2,
    explanation: "A mood style advertisement attempts to create a favorable impression by suggesting a certain feeling, conveying a peaceful tone, or displaying positive imagery."
  },
  {
    id: 77,
    lo: "principle",
    question: "Federal Mutual runs an ad highlighting its corporate sponsorship of a national safe-driving student scholarship program, linking its brand to safety. This execution style is:",
    options: [
      "Story line style",
      "Testimonial style",
      "Association style",
      "Mood style"
    ],
    answer: 2,
    explanation: "An association style draws an analogy or connection between a company/product and a highly positive activity, situation, or person."
  },
  {
    id: 78,
    lo: "principle",
    question: "Vanguard Life’s media planner wants to calculate the Cost Per Thousand Persons Reached (CPM) for a magazine ad slot costing $50,000 that reaches an audience size of 5,000,000 readers. What is the CPM?",
    options: [
      "$5.00",
      "$10.00",
      "$25.00",
      "$100.00"
    ],
    answer: 1,
    explanation: "The CPM formula is: CPM = [Cost of ad * 1,000] / Audience size. Here, [$50,000 * 1,000] / 5,000,000 = $10.00."
  },
  {
    id: 79,
    lo: "principle",
    question: "Vanguard Life is launching a brand-new, innovative long-term care insurance product. When determining advertising costs, how will product maturity affect their budget?",
    options: [
      "New products require lower budgets since consumers are already looking for them.",
      "New products usually require heavy initial spending on advertising to build awareness and shape market share.",
      "Mature products require larger budgets than new products because of high forgetting rates.",
      "Product maturity has zero impact on marketing budgets."
    ],
    answer: 1,
    explanation: "New products typically require significant, heavy initial advertising investments to build brand awareness, whereas mature products often rely on low-cost reminder ads."
  },
  {
    id: 80,
    lo: "principle",
    question: "If an insurer wants to calculate the exact Cost Per Thousand (CPM) for an online video campaign, which metrics are multiplied and divided according to the standard CPM formula?",
    options: [
      "CPM = (Cost of ad / Reach) * 1,000",
      "CPM = (Cost of ad * 1,000) / Audience size",
      "CPM = (Audience size / Cost of ad) * 1,000",
      "CPM = Total premium / 1,000"
    ],
    answer: 1,
    explanation: "In standard media metrics, CPM = [Cost of ad * 1,000] / Audience size."
  },

  // ==========================================
  // OBJECTIVE 10I: PUBLICITY OBJECTIVES & NEWSWORTHINESS (Q81 - Q90)
  // ==========================================
  {
    id: 81,
    lo: "principle",
    question: "A company’s marketing department submits a news release regarding a prominent CFO promotion and favorable year-end profits. Which primary objective of publicity does this target?",
    options: [
      "To recruit independent bank managers",
      "To provide information to the public about company achievements and initiatives",
      "To eliminate the need for premium tax payments",
      "To pretest the laboratory recall rate"
    ],
    answer: 1,
    explanation: "One of the three primary objectives of publicity is to inform the public about company achievements, awards, structural updates, and new initiatives."
  },
  {
    id: 82,
    lo: "principle",
    question: "SafeHaven Mutual sponsors clean-up activities in disaster-stricken areas and sends local media photos of their staff volunteering. This publicity is meant to accomplish which primary goal?",
    options: [
      "To bypass AIDA action requirements",
      "To manage and refine the company's image as a responsible corporate citizen",
      "To bypass state licensing requirements",
      "To calculate the cost per thousand (CPM)"
    ],
    answer: 1,
    explanation: "Managing and refining corporate image is a primary objective of publicity, helping portray the firm as a helpful, pro-social citizen."
  },
  {
    id: 83,
    lo: "principle",
    question: "A blogger publishes a scathing article accusing Apex Mutual of unfair claims delays. Apex immediately hosts a transparent press conference to present factual evidence of their fast claims resolve. This is publicity used to:",
    options: [
      "Increase print media advertising costs",
      "Mitigate the effects of negative publicity",
      "Bypass the Gramm-Leach-Bliley Act",
      "Perform laboratory pretesting"
    ],
    answer: 1,
    explanation: "Mitigating negative publicity is a third key objective of publicity. Reacting quickly and transparently can help control reputational damage."
  },
  {
    id: 84,
    lo: "principle",
    question: "Why does the general public frequently perceive information delivered via publicity (like a newspaper article or news broadcast) as far more credible than advertising?",
    options: [
      "Because publicity releases are legally approved by the SEC.",
      "Because publicity is transmitted in a news format by an independent third party, rather than paid for directly by the company.",
      "Because publicity does not have to comply with state trade regulations.",
      "Because publicity is only delivered face-to-face."
    ],
    answer: 1,
    explanation: "Since publicity is delivered by independent journalists or editors in an objective news format, viewers perceive it as more believable than paid self-promotional ads."
  },
  {
    id: 85,
    lo: "principle",
    question: "SafeHaven Mutual issues a press release about opening a single local branch office in Austin, Texas. Which media outlets should they target to ensure maximum newsworthiness?",
    options: [
      "National and global news stations to maximize reach",
      "Local and regional Austin publications and news boards",
      "FINRA and SEC official compliance filing registers",
      "Specialized banking wholesaling networks"
    ],
    answer: 1,
    explanation: "Newsworthiness depends on targeting the right audience. A local branch opening has strong appeal to local regional media but is irrelevant to national media."
  },
  {
    id: 86,
    lo: "principle",
    question: "Vanguard Life’s PR team includes the name, email, and hotlines of their Chief Information Officer at the bottom of all press releases. In publicity, this contact is the company's designated:",
    options: [
      "Registered principal",
      "Media specialist",
      "Distribution liaison",
      "Agency manager"
    ],
    answer: 1,
    explanation: "Media specialists are listed on press releases to answer journalist questions, build media relationships, and provide detailed follow-ups, increasing publication odds."
  },
  {
    id: 87,
    lo: "principle",
    question: "A newspaper editor immediately discards an insurer’s press release because it is poorly formatted, contains grammatical typos, and contains zero photos or media resources. This release lacked:",
    options: [
      "A media schedule",
      "Proper style and format",
      "Competitive parity parameters",
      "Laboratory testing statistics"
    ],
    answer: 1,
    explanation: "Media outlets reject a massive amount of corporate publicity because it is poorly prepared. Well-written, properly structured releases with clear photos/videos have higher acceptance."
  },
  {
    id: 88,
    lo: "principle",
    question: "A company’s media specialist coordinates dates to release their green-energy news wire during a slow week in summer, avoiding major national holiday weekends or predicted industry conferences. This strategy ensures the release:",
    options: [
      "Bypasses New York Regulation 60 disclosures",
      "Does not directly compete with other major news stories",
      "Uses a steady pulsing schedule",
      "Limits reach to regional bank employees"
    ],
    answer: 1,
    explanation: "Natural disasters and hard news take priority. Scheduling publicity releases during quiet, non-peak times increases the likelihood that journalists will publish them."
  },
  {
    id: 89,
    lo: "principle",
    question: "An insurance company wishes to announce a massive merger affecting policyholders across the entire nation. Which media types represent the correct target for this news?",
    options: [
      "Only local neighborhood community newsletters",
      "National financial news channels and publications",
      "Internal training sales aids only",
      "Specialised bank platform employee bulletin boards"
    ],
    answer: 1,
    explanation: "Because a national merger affects policyholders coast-to-coast, it holds strong national newsworthiness and should be communicated through nationwide networks."
  },
  {
    id: 90,
    lo: "principle",
    question: "SafeHaven Mutual wants to evaluate if they should run video ads on YouTube or publish print ads. Publicity efforts, however, are unique because:",
    options: [
      "Insurers have complete authority over when and how the media transmits their news releases.",
      "Insurers don't incur direct media costs because they don't buy the time or space, but they have no control over if or how the data is actually printed.",
      "Publicity is prohibited from showing variable annuity options.",
      "Publicity must be registered directly under ERISA guidelines."
    ],
    answer: 1,
    explanation: "While publicity does not carry direct media space/time costs, the marketer surrenders control over whether, when, or how the visual content is compiled and printed."
  },

  // ==========================================
  // OBJECTIVE 10J: EVALUATING EFFECTIVENESS (Q91 - Q95)
  // ==========================================
  {
    id: 91,
    lo: "principle",
    question: "SafeHaven Mutual shows target consumers three different ad layouts, asking them to evaluate the visual layouts, understandability, and messaging appeal of each. This type of pretesting is:',",
    options: [
      "Laboratory test",
      "Direct comparison test (or portfolio test)",
      "Prerollout test",
      "Aided recall test"
    ],
    answer: 1,
    explanation: "A direct comparison (or portfolio) test involves showing target consumers several mock ads and asking them to rate specific aspects to see which appeals work best."
  },
  {
    id: 92,
    lo: "principle",
    question: "In scientific pretesting, researchers hook up volunteers to biometric devices to map eye tracking, changes in heart rates, and blood pressure while they watch an insurance TV ad. This is a:",
    options: [
      "Portfolio comparison test",
      "Laboratory test",
      "Prerollout test",
      "Unaided recall test"
    ],
    answer: 1,
    explanation: "Laboratory tests expose customers to ads while utilizing specialized diagnostic gear to record physiological responses, checking if an ad captures attention."
  },
  {
    id: 93,
    lo: "principle",
    question: "Before launching a multimillion-dollar national campaign, SafeHaven Mutual runs their ad for one week in a single mid-western city and monitors local consumer reactions. This is a:",
    options: [
      "Laboratory test",
      "Direct comparison test",
      "Prerollout test",
      "Recognition test"
    ],
    answer: 2,
    explanation: "A prerollout test exposes target consumers to an advertisement in a real-life, limited context (e.g., one city/paper) to forecast full-scale performance."
  },
  {
    id: 94,
    lo: "principle",
    question: "Vanguard Life’s research department calls target consumers and asks, 'Do you recall seeing any life insurance advertisements on TV during last night's talk show?' This evaluation is a:",
    options: [
      "Direct laboratory test",
      "Unaided recall test",
      "Aided recall test",
      "Recognition test"
    ],
    answer: 2,
    explanation: "An aided recall test provides cues or prompts (e.g., naming a specific time, category, or talk show) to check if consumers remember seeing the advertisement."
  },
  {
    id: 95,
    lo: "principle",
    question: "SafeHaven Mutual prints a direct link on a print ad inviting readers to visit a specific webpage to download a free retirement workbook. They track the total number of clicks generated. This is:",
    options: [
      "Laboratory test",
      "Inquiry test",
      "Recognition test",
      "Attitude pretest"
    ],
    answer: 1,
    explanation: "Inquiry tests measure the effectiveness of an advertisement by counting the volume of responses, calls, or digital link-clicks it actively generates."
  },

  // ==========================================
  // OBJECTIVE 10K: REGULATION & DISCLOSURE DOCUMENTS (Q96 - Q100)
  // ==========================================
  {
    id: 96,
    lo: "principle",
    question: "The NAIC Advertisements of Life Insurance and Annuities Model Regulation establishes strict rules regarding promotional materials. Under these rules, which of the following is prohibited?",
    options: [
      "Using the term 'life insurance' in the product's official title",
      "Minimizing, obscuring, or hiding required disclosures within the tiny text of an advertisement",
      "Including standard policy summaries",
      "Pretesting advertisements inside a regional laboratory"
    ],
    answer: 1,
    explanation: "The NAIC Model regulation prohibits insurers from burying key risk disclosures in tiny, illegible text or minimizing/hiding them to mislead buyers."
  },
  {
    id: 97,
    lo: "principle",
    question: "According to state regulations, when an insurer advertises a policy with graded or nonlevel premiums, they must follow which direct compliance disclosure rule?",
    options: [
      "They are prohibited from advertising nonlevel products entirely.",
      "They must prominently describe any premium changes and clearly disclose if the insurer can adjust premiums during the policy term.",
      "They must register the advertisement as an SEC prospectus.",
      "They can ignore disclosures if the buyer has a high-school education."
    ],
    answer: 1,
    explanation: "Under Advertisements Model Rules, any premium modifications or rights to adjust nonlevel premiums during the term must be prominently disclosed inside the ad text."
  },
  {
    id: 98,
    lo: "principle",
    question: "Vanguard Life provides prospective buyers with a standardized booklet that describes in plain, non-technical language the basic types of policies, how to calculate coverage needs, and factors to weigh. This document is the:",
    options: [
      "Policy Summary",
      "Life Insurance Buyer's Guide",
      "Vesting Schedule Index",
      "SEC Prospectus Draft"
    ],
    answer: 1,
    explanation: "The Life Insurance Buyer's Guide is a standardized document that explains basic life insurance types, needs calculations, and buying guides in descriptive, plain language."
  },
  {
    id: 99,
    lo: "principle",
    question: "A producer hands an applicant a specific document containing detailed cost indexes, the names and addresses of the insurer, annual premium amounts, basic death benefits, and cash surrender values for the first five policy years. This document is the:",
    options: [
      "Buyer's Guide",
      "Policy Summary",
      "Producer Licensing Model act",
      "AIDA response chart"
    ],
    answer: 1,
    explanation: "A policy summary contains specific, numerical details about the actual contract being purchased, including custom premium structures, indexes, and surrender benefits for the early years."
  },
  {
    id: 100,
    lo: "principle",
    question: "When an insurer distributes variable life or variable annuity products to consumers in the United States, which specialized disclosure document is legally mandated under federal securities laws?",
    options: [
      "A Policy Summary sheet only",
      "The NAIC Unfair Trade Practice index",
      "A prospectus",
      "The state CE certification form"
    ],
    answer: 2,
    explanation: "Because variable products carry investment risks regulated under federal securities codes, insurers must deliver a prospectus describing key risks, fees, and objectives to buyers."
  }
];
